{{- if .Values.plugin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "console-plugin-nvidia-gpu.serviceAccountName" . }}
  labels:
    {{- include "console-plugin-nvidia-gpu.labels" . | nindent 4 }}
  {{- with .Values.plugin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

